// C++ Code automatically generated by 'XSiSi 2.0'
// Emitted at Sun Feb 07 08:50:23 CET 2021

// Please read the documentation!

#ifndef _callSiSi_hh_
#define _callSiSi_hh_

#include "development/SiSi.hh"         // Includes lot of SiSi's header files.

// Here are additional class and/or struct definitions,
// needed by SiSi's parser:
#include "MySiSi.hh"

#include "variables.h"

class SiSi
{
public:
  // public methods:
  static bool parseSimulation(int argc, char* argv[]);
  static bool parseSimulation(const char* simulationFile, const char* program);
  static void abort();                 // Should be called at abortion.
  static void finalize();              // Should be called at termination.
  // public variables:
  static String       SimulationName;  // Full name of the simulation.
  static String       ModelName;       // Full name of the model.
  static String       ModelPath;       // Path of the executable model.
  static TwoWayList*  IncludeFiles;    // Names of all included files.
  static TwoWayList*  OutputVariables; // Includes all output variables.
  static TwoWayList*  VariationVariables; // Includes all output variables.
  static LogFile      logFile;         // The file for Job controlling system.
  static ResultWriter resultWriter;    // Declaration of ResultWriter.
  static String       resultFilename;  // Name of the result file.
  static String       simulationPath;  // Path of the simulation file.
};

#endif // _callSiSi_hh_
