// C++ Code automatically generated by 'XSiSi 2.0'
// Emitted at Fri Sep 05 18:38:31 EDT 2014

// Please read the documentation!

// Please note: This file will not be overwritten in future times.

#ifndef _MySiSi_hh_
#define _MySiSi_hh_
// Here you can insert class and/or struct definitions
// needed by SiSi's parser.
// (You can also place #include's here!)
#endif // _MySiSi_hh_
