/* Declaration of pointer to variation parameters: */
  extern double *VAR_VAL[199];
  extern char VAR_NAMES[199][22];
  extern int num_variat_parser;

/* Declaration of parameters and variables of simulation: */
  extern double Time;
  extern double TimeStart;
  extern double TimeEnd;
  extern double TimeStep;
  extern double OutputStep;
  extern long RandomInit;
  extern double** Conc;
  extern unsigned int RowsOfConc;
  extern unsigned int ColumnsOfConc;
  extern String*      HeadOfConc;
  extern double** trans;
  extern unsigned int RowsOftrans;
  extern unsigned int ColumnsOftrans;
  extern String*      HeadOftrans;
  extern double** aRtrans;
  extern unsigned int RowsOfaRtrans;
  extern unsigned int ColumnsOfaRtrans;
  extern String*      HeadOfaRtrans;
  extern double* exposition;
  extern unsigned int LengthOfexposition;
  extern double* CostAcc;
  extern unsigned int LengthOfCostAcc;
  extern String MovieResFile;
  extern String VarResFile;
  extern String VarIndexFile;
  extern long VarActive;
  extern long NumDice;
  extern long MonteCarlo;
  extern long VarOutputStep;
  extern long AnalysisType;
  extern long** parindex;
  extern unsigned int RowsOfparindex;
  extern unsigned int ColumnsOfparindex;
  extern String*      HeadOfparindex;
  extern long DataActive;
  extern long DataCountryIndex;
  extern double critfatal;
  extern double* err_data_weights;
  extern unsigned int LengthOferr_data_weights;
  extern double data_off_tim;
  extern long Experiment;
  extern long* IndExp;
  extern unsigned int LengthOfIndExp;
  extern double storetim;
  extern double Zero;
  extern double mindelt;
  extern double maxdelt;
  extern double relrate;
  extern double relchange;
  extern double accuracy;
  extern long method;
  extern double InfectDens;
  extern double* age_dist;
  extern unsigned int LengthOfage_dist;
  extern double init_age;
  extern double m_age;
  extern double* med_ages;
  extern unsigned int LengthOfmed_ages;
  extern double* temp_min;
  extern unsigned int LengthOftemp_min;
  extern double* temp_max;
  extern unsigned int LengthOftemp_max;
  extern double* latitude;
  extern unsigned int LengthOflatitude;
  extern double* excessm;
  extern unsigned int LengthOfexcessm;
  extern double* houseold;
  extern unsigned int LengthOfhouseold;
  extern double time_shut;
  extern double period_vacc;
  extern double vacc_frac;
  extern double** ForcData;
  extern unsigned int RowsOfForcData;
  extern unsigned int ColumnsOfForcData;
  extern String*      HeadOfForcData;
  extern double beta_max;
  extern double recov;
  extern double mort;
  extern double sub_beta;
  extern double social;
  extern double catchup;
  extern double acc_catch;
  extern double tlag;
  extern double flexibility;
  extern double behave;
  extern double behave_rate;
  extern double temp_ampl;
  extern double weekampl_sub;
  extern double week_ampl;
  extern double sun_ampl;
  extern double temp_width;
  extern double q10_fatal;
  extern double* attack;
  extern unsigned int LengthOfattack;
  extern double relaxs;
  extern double travel;
  extern double DecStart;
  extern double parvar1;
  extern double parvar2;
  extern double** data;
  extern unsigned int RowsOfdata;
  extern unsigned int ColumnsOfdata;
  extern String*      HeadOfdata;

/* Declaration of additional output variables: */

